module.exports = {
  siteUrl: "https://www.yourdomain.tld",
  title: "National Transport Data Bank",
  titleTemplate: "NTD | National Transport Databank ",
  description:
    "Nigeria Transport Data Service, TDS, manages the collection, storage, management and analysis of Transport related data in Nigeria. Access Nigeria Railway data, Nigeria Road data, Nigeria air data, Nigeria pipeline  and Nigeria water transport data in one place.",
  url: "tdsnigeria.ng",
  image: "src/images/HeaderLogo.png",
  twitterUsername: "@devobs",
  ogLanguage: "en_US",
  siteLanguage: "en",
  headline: "Collecting transport data in Nigerias",
  contentType: "text/html; charset=UTF-8",
  keywords: [
    "data",
    "Nigeria transport",
    "Transport Data",
    "Nigeria Government",
    "Transport Data Services",
    "Miniter of Transport",
    "Air transport",
    "Nigeria Railways",
    "Nigeria Air",
    "Airport",
    "Road Transport Data",
    "tds",
    "Water Transport",
    "Nigeria transport data",
  ],
};
